### ISSUE TITLE
Remove the following files from the repo

### ISSUE THREAD

**Issue by cromanpa94** [dkangsimUA/kangsim_capstone#1]
These two files are not needed. Please remove them from the repo and add them to your `.gitignore`.

https://github.com/dkangsimUA/kangsim_capstone/blob/main/._kangsim_capstone.Rproj

https://github.com/dkangsimUA/kangsim_capstone/blob/main/.DS_Store

**Comment by cromanpa94** [comment]
Adding one more to the list: https://github.com/dkangsimUA/kangsim_capstone/blob/main/kangsim_capstone.Rproj

**Comment by dkangsimUA** [comment]
I assume these files are required for the GitHub desktop to stay synced. When the repo is transferred to PI's repo, I will remove these files.
