### ISSUE TITLE
Please explain the expected structure for `here`

### ISSUE THREAD

**Issue by cromanpa94** [dkangsimUA/kangsim_capstone#4]
Please make sure that you explain whether an R project is needed for `here`

https://github.com/dkangsimUA/kangsim_capstone/blob/699c74bf023fa6758afef515588801d4e1530d83/capstone_reproducible_script.qmd#L72

**Comment by dkangsimUA** [comment]
Rproj is not needed if we use the `here` package. I will remove Rproj file.
